name: Twitter-to-Telegram Bot
on:
  schedule:
    - cron: "*/3 * * * *"  # Changed from 5 to 3 minutes for faster sync
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    timeout-minutes: 10  # Prevents hanging jobs
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'  # Explicit version for stability
          cache: 'npm'  # Faster installs
          
      - name: Install dependencies
        run: npm ci  # Uses package-lock.json for exact versions
        
      - name: Run Twitter-to-Telegram bot
        run: node index.js
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHANNEL: ${{ secrets.TELEGRAM_CHANNEL }}
          TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
          TWITTER_API_SECRET: ${{ secrets.TWITTER_API_SECRET }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_SECRET: ${{ secrets.TWITTER_ACCESS_SECRET }}
